name: Authme
version: '${project.version}'
main: online.nyalian.authme.Authme
api-version: 1.18
authors: [ nyalian ]
description: Authme for login
website: nyalian.online
commands:
  login:
    aliases:
      - "lg"
      - "l"
      - "L"
    description: "Login or register"
    usage: "/login <PASSWORD>"